[package]
name = "rsync-nvim"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
luajit = ["mlua/luajit"]

[dependencies]
toml = "0.7.3"
mlua = {version = "0.8.8", features = ["luajit", "vendored", "module", "serialize"]}
