name: Testing

on:
  push:
    branches: [master]
  pull_request:

jobs:
  busted:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: macos-latest
            is_mac: 1
          - os: ubuntu-latest
            is_unix: 1
    name: busted
    runs-on: ${{ matrix.os }}
    steps: 
      - name: checkout
        uses: actions/checkout@v3
      - name: install cargo
        uses: dtolnay/rust-toolchain@stable
      - name: restore cache
        uses: Swatinem/rust-cache@v2
      - name: build rsync
        run: |
          make build
      - name: install plenary.nvim
        uses: actions/checkout@v3
        with:
          repository: nvim-lua/plenary.nvim
          path: plenary.nvim
      - name: install luacov
        if: ${{ matix.is_unix }}
        run: |
          sudo apt install luarocks
          sudo luarocks install luacov
          sudo luarocks install cluacov
          sudo luarocks install luacov-console
      - name: install neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly
      - name: run test
        if: ${{ matrix.is_unix }}
        run: NOCLEAN=1 make testcov
      - name: run on macos
        if: ${{ matrix.is_mac }}
        run: make test
      - name: upload coverage report
        if: ${{ matrix.is_unix }}
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: luacov.report.out, luacov.stats.out
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
