name: Testing

on:
  push:
    branches: [master]
  pull_request:

jobs:
  busted:
    name: busted
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v3
      - name: install plenary.nvim
        run: |
          sudo apt-get install -y luarocks
          sudo luarocks install plenary.nvim
      - name: install neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly
      - name: run test
        run: make test
