name: Testing

on:
  push:
    branches: [master]
  pull_request:

jobs:
  busted:
    name: busted
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v3
      - name: install cargo
        uses: dtolnay/rust-toolchain@stable
      - name: restore cache
        uses: Swatinem/rust-cache@v2
      - name: build rsync
        run: |
          make build
      - name: install plenary.nvim
        uses: actions/checkout@v3
        with:
          repository: nvim-lua/plenary.nvim
          path: plenary.nvim
      - name: install neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly
      - name: run test
        run: make testcov
