name: Linting and style checking

on:
  push:
    branches: [master]
  pull_request:

jobs:
  luacheck:
    name: luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lunarmodules/luacheck@v1
        with: 
          args: lua/rsync

  stylua:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --color always --check lua/
  cargo-fmt:
    name: cargo format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
  cargo-clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install cargo
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: restore cache
        uses: Swatinem/rust-cache@v2
      - name: run clippy
        run: cargo clippy
